# Email Worker 配置文件
name = "temp-mail-email-worker"
main = "email-worker.js"
compatibility_date = "2024-01-01"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "TEMP_MAILS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# 环境变量
[vars]
DOMAIN = "your-domain.com"

# 生产环境配置
[env.production]
kv_namespaces = [
  { binding = "TEMP_MAILS", id = "your-kv-namespace-id" }
]

[env.production.vars]
DOMAIN = "your-domain.com"

# 开发环境配置
[env.development]
kv_namespaces = [
  { binding = "TEMP_MAILS", id = "your-preview-kv-namespace-id" }
]

[env.development.vars]
DOMAIN = "dev.your-domain.com"
