name = "temp-mail-system"
compatibility_date = "2024-01-01"

# Pages 配置
[env.production]
account_id = "your-account-id"
pages_build_output_dir = "public"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "TEMP_MAILS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# 环境变量
[vars]
AUTH_TOKEN = "your-secret-auth-token"
DOMAIN = "your-domain.com"

# Email Workers 配置（需要单独配置）
# 这个配置用于 Email Worker，不是 Pages
# 需要在 Cloudflare Dashboard 中单独创建 Email Worker

# 开发环境配置
[env.development]
kv_namespaces = [
  { binding = "TEMP_MAILS", id = "your-dev-kv-namespace-id" }
]

[env.development.vars]
AUTH_TOKEN = "dev-secret-token"
DOMAIN = "dev.your-domain.com"
