# Cloudflare Pages 配置
name = "temp-mail-system"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "TEMP_MAILS"
id = "435fdf61f77c4f02950cd20ff71bef1a"
preview_id = "435fdf61f77c4f02950cd20ff71bef1a"

# 环境变量
[vars]
AUTH_TOKEN = "your-secret-token"
DOMAIN = "your-domain.com"
EPIN = "your-epin"
